program: main.py
method: grid
parameters:
  dataset:
    value: "icdm"
  K:
    value: 10
  ggd-lr:
    value: 0.0001
  classifier-lr:
    value: 0.0005
  n-hidden:
    value: 64
  n-layers:
    values: [1, 4] 
  proj_layers:
    value: 1
  n-ggd-epochs:
    value: 1
  n-classifier-epochs:
    value: 300
  gnn_encoder:
    value: "gcn"
  proj_layers:
    value: 1
  power:
    values: [0, 1, 5, 10, 15, 20]
  wandb:
    value: True
